# Part 1 :

## Importing Libraries {style="color : black"}

```{r}
library(Hmisc)
library(pls)
library(data.table)
```

## Reading data set

```{r}
DM.dt <- fread(file.path("dataset.csv"))
DM <- DM.dt[,.(X1,X2,X3,Y)]
head(DM.dt)

```

```{r}
do.call(cbind, lapply(DM, summary))
```

```{r}
boxplot(Y~X1,data=DM.dt,main="Distribution de Y par X1",xlab="X1",ylab="Y",col="yellow",border="brown")
```

```{r}
boxplot(Y~X2,data=DM.dt,main="Distribution de Y par X2",xlab="X2",ylab="Y",col="yellow",border="brown")
```

```{r}
boxplot(Y~X3,data=DM.dt,main="Distribution de Y par X3",xlab="X3",ylab="Y",col="yellow",border="brown")
```

```{r}
DM_Matrix<-as.matrix(DM)
rcorr(DM_Matrix, type=c("pearson","spearman"))
```

```{r}
pairs(~X1+X2+X3+Y , data=DM , main = "Scatter Matrix")
```

# Part 3 :

```{r}
DM_Matrix<-as.matrix(DM.dt)
rcorr(DM_Matrix, type=c("pearson","spearman"))
```

```{r}
# Regression multiple Y=f(X1..X8)
lm<-lm(formula = Y ~ 0 + X1 + X2+ X3 + X4 + X5 +X6 + X7 + X8, data=DM.dt)
#print 
print(lm)
#summary
print(summary(lm))
```

```{r}
Scale_DM<-scale(DM.dt)
colnames(Scale_DM)<- c("Y_cn","X1_cn","X2_cn","X3_cn","X4_cn","X5_cn","X6_cn","X7_cn","X8_cn")
DT_scale<- cbind(DM.dt,Scale_DM)
```

#### Construction de T1

```{r}

DT_scale<-DT_scale[,':='(T1=(1/sqrt(0.48^2 + 0.73^2 + 0.87^2 + 0.88^2 + 0.88^2 + 0.88^2 + 0.88^2 + 
                                    0.88^2))*((-0.48*X1_cn)+(0.73*X2_cn)+(0.87*X3_cn) +(0.88*X4_cn)+
                                                (0.88*X5_cn)+(0.88*X6_cn)+(0.88*X7_cn) +(0.88*X8_cn)))]
```

#### Construction de T2

```{r}
# Regression y sur T1 et Xj j=1..8
#pour chercher les variables contribuant de manière significative à la construction de T2

lm11<-lm(formula = Y_cn ~ 0 + T1 + X1_cn, data=DT_scale)
print(summary(lm11))

lm12<-lm(formula = Y_cn ~ 0 + T1 + X2_cn, data=DT_scale)
print(summary(lm12))

lm13<-lm(formula = Y_cn ~ 0 + T1 + X3_cn, data=DT_scale)
print(summary(lm13))

lm14<-lm(formula = Y_cn ~ 0 + T1 + X4_cn, data=DT_scale)
print(summary(lm14))

lm15<-lm(formula = Y_cn ~ 0 + T1 + X5_cn, data=DT_scale)
print(summary(lm15))

lm16<-lm(formula = Y_cn ~ 0 + T1 + X6_cn, data=DT_scale)
print(summary(lm16))

lm17<-lm(formula = Y_cn ~ 0 + T1 + X7_cn, data=DT_scale)
print(summary(lm17))

lm18<-lm(formula = Y_cn ~ 0 + T1 + X8_cn, data=DT_scale)
print(summary(lm18))
```

#### regression de Y sur T1 :

```{r}
lm_PLS<-lm(formula = Y ~ T1 , data=DT_scale)
print(summary(lm_PLS))
```

#### equation of PLS regression :

```{r}

# Y = 8.37267 + 0.25097*T1
# Y = 8.37267 + 0.25097*0.43[(-0.48*X1_cn)+(0.73*X2_cn)+(0.87*X3_cn) +(0.88*X4_cn)+
#                                                (0.88*X5_cn)+(0.88*X6_cn)+(0.88*X7_cn) +(0.88*X8_cn)]
#Y=8.37267 - 0.05180021*X1 + 0.07877948*X2 + 0.09388788*X3 + 0.09496705*X4 + 0.09496705*X5 + 0.09496705*X6 + 0.09496705*X7 +0.09496705*X8

DT_scale<-DT_scale[,':='(Y_fitted=(8.37267 + (-0.05180021*X1_cn)+(0.07877948* X2_cn)+(0.09388788*X3_cn)+
                      (0.09496705* X4_cn)+(0.09496705* X5_cn)+(0.09496705* X6_cn)+(0.09496705* X7_cn)+
                        (0.09496705* X8_cn)))]
```

```{r}
DT_scale$Y_fitted[seq(25,30)]
```

```{r}
xdata <- seq(1,30)
plot(xdata , DT_scale$Y, type="o", col="blue", pch="o", lty=1, ylim=c(7,11),main="'Y' vs 'Y_fitted'",
     ylab="Y", )
# Add second curve to the same plot by calling points() and lines()
# Use symbol '*' for points.
points(xdata,  DT_scale$Y_fitted, col="red", pch="*")
lines(xdata,  DT_scale$Y_fitted , col="red",lty=2)
legend(24,11,legend=c("Y", "Y_fitted"), col=c("blue", "red"), lty=1:2, cex=0.8)
```

```{r}
DT_scale$Y_fitted
```

```{r}
DT_scale$Y

```

```{r}
write.csv(DT_scale,"./test.csv", row.names = FALSE)
```
